database_connection:
  type: MYSQL
  host: localhost
  port: 3306
  database: db_name
  user: db_user
  password: db_password

queries:
  get_balance:
    - "SELECT amount FROM balance WHERE player = {{player_uuid}}"

currency:
  symbol: "€"
  name_singular: "Euro"
  name_plural: "Euros"